### PR TITLE
When an item is completed, move to DONE_FILE

### PR DESCRIPTION
**Pull request by blairjordan**
Copy completed items to a "done" file before removing them.

Default `$DONE_FILE` is `~/.rofi_todos_done`

### CODE REVIEW

**Comment by claudiodangelis** [comment]
Thanks for your contribution! It would be nice to have a way to disable it though... Can you think about something? If not, I can take care of that myself.

Thanks!

**Comment by blairjordan** [comment]
@claudiodangelis The script is very simple with no external config (which is what I like about it), so perhaps we could define and use another var:
`RETAIN_DONE_ITEMS=false` ?

**Comment by claudiodangelis** [comment]
@blairjordan what about checking the value of the `$DONE_FILE` variable? If user doesn't want to keep done items they can leave the variable unset:

```bash
if [[ ! -z "$DONE_FILE" ]]; then
    echo "${*}" >> "${DONE_FILE}"
fi
```

**Comment by blairjordan** [comment]
I like that approach. I've updated the PR and README.

**Comment by claudiodangelis** [comment]
@blairjordan thank you very much for your contribution!

**Pull request merged**
